config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get 'todos' =>'todos#index'
    post 'todos' => 'todos#create'
    get 'todos:id', to:'todos#show', as:'todo'
    get 'todos/new'
    get '/todos/:id/edit', to:'todos#edit', as:'edit'
    patch '/todos/:id', to:'todos#update'
    delete '/todos/:id', to:'todos#destroy', as:'destroy'
    get '/todos:id/complete', to:'todos#complete', as:'completed'
    get '/todos/list'




root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create     
        todo = Todo.new(todo_params)
        if todo.save
          redirect_to todos_path, notice: 'creado con exito'
        else
          redirect_to todos_new_path, notice: 'ha ocurrido un error'
        end
    end


    def show
        @todo = Todo.find(params[:id])
    end


    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
            if @todo.update(todo_params)
                redirect_to @todo, notice: 'actualizado con exito'
            else
                redirect_to root_path(@todo), notice: 'intentalo nuevamente'
            end
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to root_path, notice:'se eliminó el registro'
    end

    def complete
        @todo = Todo.find(params[:id])
        if @todo.save
            redirect_to root_path, notice:'se ha guardado el registro'
        else
            redirect_to root_path(@todo), notice:'no se ha guardado el registro'
        end    
    end

    def list
        @todos = Todo.all

    end
    private

    def todo_params
        params.require(:todo).permit(:description, :completed)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg  navbar-dark bg-primary fixed-top">
      <a class="navbar-brand">APP ToDo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="<%= root_path %>">Index <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= todos_path %>">List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= todos_new_path %> ">New form</a>
            </li>
          </ul>
      </div>
  </nav>
    
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/edit.html.erb
<div class="container">
  <h1>Editar el Todo</h1>

  <%= form_with model: @todo, local: true do |f| %>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, id: :todo_description,class:'from-text' %>
    </div>
    <div class="form-group">
      <%= f.label :completed %>
      <%= f.text_area :completed, id: :todo_completed, class:'form-text' %>
    </div>
    <%= f.submit 'Actualizar', class:'btn btn-primary' %>
  <% end %>
</div>

app/views/todos/index.html.erb
<h1>ToDo List App </h1>
<br>
<%= link_to 'Crear ToDo', todos_new_path, class:'btn btn-success' %>

<br>

<table>
<br>
    <tr>
        <th>Description:</th>

    </tr>

    <% @todos.each do |todo| %>    
        <tr>  
            <td><%= todo.description %>
            <td><% todo.completed %>
            <%= link_to 'Show', todo_path(todo), class:'btn btn-success' %>
            <%= link_to 'Edit', edit_path(todo), class:'btn btn-warning' %>
            <%= link_to 'Destroy', destroy_path(todo), class:'btn btn-danger' %>
            <%= link_to 'Completed', completed_path(todo), class:'btn btn-info' %>
        </tr>
           
    <% end %>  

</table>

 

app/views/todos/list.html.erb
<section>
    <div class="row align-items-start">
 
		<div class="col">
			Columna 1
		</div>
 
		<div class="col">
			Columna 2
		</div>
 
		<div class="col">
			Columna 3
        </div>
        
        <div class="col">
            Columna 4
        </div>

        <div class="col">
            Columna 5
        </div>

        <div class="col">
            Columna 6
        </div>
 
	</div>
 
</section>

<section>
    <div class="row align-items-start">
 
		<div class="col">
			Columna 1
		</div>
 
		<div class="col">
			Columna 2
		</div>
 
		<div class="col">
			Columna 3
        </div>
        
        <div class="col">
            Columna 4
        </div>

        <div class="col">
            Columna 5
        </div>

        <div class="col">
            Columna 6
        </div>
 
	</div>
 
</section>

app/views/todos/new.html.erb
<div class="container">
  <h1>Ingresa un nuevo ToDo</h1>

  <%= form_with model: @todo, local: true do |f| %>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, id: :todo_description,class:'from-text' %>
    </div>
    <div class="form-group">
      <%= f.label :completed %>
      <%= f.text_area :completed, id: :todo_completed, class:'form-text' %>
    </div>
    <%= f.submit 'Enviar', class:'btn btn-primary' %>
  <% end %>
</div>

app/views/todos/show.html.erb
<div class="container">
    <h2>Descripción de ToDo</h2>
        <br>
        <strong>Description:</strong>  <%= @todo.description %>
        <br>
        <strong>Completed:</strong>  <%= @todo.completed %>
        <br>
    
</div>